/**
 * @module @sentinellium/types
 * @description Shared type definitions for the Sentinellium platform.
 *
 * This package contains all shared TypeScript types and interfaces used
 * across the extension, enterprise console, and API services.
 */

// ─── Threat & Alert Types ───────────────────────────────────────────

/** Severity levels for security threats, ordered by urgency. */
export type ThreatSeverity = "critical" | "high" | "medium" | "low" | "info";

/** Categories of threats that Sentinellium can detect. */
export type ThreatCategory = "phishing" | "deepfake" | "dlp" | "unknown";

/** Current status of a security alert in the system. */
export type AlertStatus = "active" | "acknowledged" | "resolved" | "dismissed";

/** Provenance verification status for media assets. */
export type ProvenanceStatus =
  | "verified"
  | "unverified"
  | "tampered"
  | "unknown";

/**
 * A security alert generated by one of the detection engines.
 * Forwarded to the enterprise console for aggregation.
 */
export interface SecurityAlert {
  /** Unique identifier for this alert. */
  id: string;
  /** ISO-8601 timestamp of when the alert was generated. */
  timestamp: string;
  /** Severity classification of the threat. */
  severity: ThreatSeverity;
  /** Which detection engine produced this alert. */
  category: ThreatCategory;
  /** Current lifecycle status of the alert. */
  status: AlertStatus;
  /** Human-readable title summarizing the threat. */
  title: string;
  /** Detailed description of the threat and its context. */
  description: string;
  /** The URL where the threat was detected. */
  url: string;
  /** The domain extracted from the URL. */
  domain: string;
  /** Confidence score from the detection engine (0.0–1.0). */
  confidence: number;
  /** Unique identifier of the extension instance that generated this alert. */
  instanceId: string;
  /** Optional metadata specific to the detection engine. */
  metadata?: Record<string, unknown>;
}

// ─── Extension Instance Types ───────────────────────────────────────

/** Health status of a connected extension instance. */
export type InstanceStatus = "online" | "offline" | "degraded";

/**
 * Represents a deployed Sentinellium extension instance
 * registered with the enterprise management console.
 */
export interface ExtensionInstance {
  /** Unique identifier for this extension instance. */
  id: string;
  /** Human-readable name (e.g., "John's Workstation — Chrome"). */
  name: string;
  /** Current connectivity status. */
  status: InstanceStatus;
  /** Installed extension version string. */
  version: string;
  /** Browser and OS environment information. */
  userAgent: string;
  /** ISO-8601 timestamp of last heartbeat received. */
  lastSeen: string;
  /** ISO-8601 timestamp of initial registration. */
  registeredAt: string;
  /** Tenant identifier for multi-tenancy isolation. */
  tenantId: string;
}

// ─── Policy Types ───────────────────────────────────────────────────

/**
 * A security policy that can be distributed to extension instances.
 * Policies control which engines are active and their configurations.
 */
export interface SecurityPolicy {
  /** Unique identifier for this policy. */
  id: string;
  /** Human-readable policy name. */
  name: string;
  /** Detailed description of the policy's purpose and scope. */
  description: string;
  /** Semantic version of the policy schema. */
  version: string;
  /** Whether the phishing detection engine is active. */
  phishingEnabled: boolean;
  /** Whether the C2PA deepfake defense engine is active. */
  deepfakeEnabled: boolean;
  /** Whether the Shadow AI DLP engine is active. */
  dlpEnabled: boolean;
  /** List of domains to exclude from scanning. */
  allowlistedDomains: string[];
  /** Custom regex patterns for PII detection in the DLP engine. */
  customPiiPatterns: string[];
  /** ISO-8601 timestamp of last modification. */
  updatedAt: string;
}

// ─── Telemetry Types ────────────────────────────────────────────────

/**
 * Privacy-preserving telemetry data from an extension instance.
 * Contains only aggregated counts — no PII or browsing data.
 */
export interface TelemetryPayload {
  /** Extension instance that generated this telemetry. */
  instanceId: string;
  /** ISO-8601 timestamp of the reporting period start. */
  periodStart: string;
  /** ISO-8601 timestamp of the reporting period end. */
  periodEnd: string;
  /** Count of pages scanned during this period. */
  pagesScanned: number;
  /** Count of threats detected during this period. */
  threatsDetected: number;
  /** Count of DLP interventions during this period. */
  dlpInterventions: number;
  /** Count of C2PA verifications performed during this period. */
  mediaVerified: number;
  /** Average inference latency in milliseconds. */
  avgInferenceMs: number;
}

// ─── API Response Types ─────────────────────────────────────────────

/**
 * Standard API response envelope for type-safe communication.
 * @template T The type of the response data payload.
 */
export interface ApiResponse<T> {
  /** Whether the request was successful. */
  success: boolean;
  /** The response data payload. */
  data: T;
  /** Optional error information if success is false. */
  error?: {
    /** Machine-readable error code. */
    code: string;
    /** Human-readable error message. */
    message: string;
  };
}

/**
 * Paginated API response for list endpoints.
 * @template T The type of each item in the results array.
 */
export interface PaginatedResponse<T> {
  /** Array of result items for the current page. */
  items: T[];
  /** Total count of items across all pages. */
  total: number;
  /** Current page number (1-indexed). */
  page: number;
  /** Number of items per page. */
  pageSize: number;
  /** Whether there are more pages after the current one. */
  hasMore: boolean;
}
